---
title: "test"
output: pdf_document
date: "2025-04-08"
---

# Methodology

## Scoring

The interview notes were reviewed to identify quantitative scores applying following criteria (in this ordered):

-   *C1 (score available)*: When a clear and unique self-declared score was provided, this was used as a score. In case the interviewee provided two scores (e.g.: 4 or 5), it was used the average (4.5). For those answers were alternative were provided for gear/target, create separate scoring.
-   *C2 (score to be interpreted)*: Answers that were providing meaningful text but not a clear number, or that were considered worth of further attention, were scored as 999.
-   *C3 (does not apply)*: Answers that were missing because the event/condition does not apply were scored as -999. When the “does not apply” was identified in more than 50% of the answers, the combination of fishing style-event was excluded from further analysis.
-   *C4 (can't answer)*: Answers that were missing because people did not have a personal experience to refer but refers to an event that is relevant (i.e.: if during a storm you never go out, you might don’t know about how catchability changes) were scored as -998.
-   *C5 (garbled)*: Answers that were not coherent with the question were scored -997

```{r , echo=FALSE,message = FALSE,results = 'asis', message=F}
library(tidyverse)
library(kableExtra)
scoring.system=data.frame(Score=c('x', 999, -999, -998, -997), Type=paste('C', 1:5), Description = c('Number (x) available', 'To be interpreted','Does not apply', 'Cant answer', 'Garbled'))

kableExtra::kable(scoring.system, caption = 'coding system used to categorise answers according to their interpretation')%>%
  kable_styling(font_size = 8)%>% 
            column_spec(1, width = "1cm")%>%
            column_spec(2, width = "1cm")%>%
            column_spec(2, width = "3cm")
```


## Interpretation

A structured coding approach was applied to those answers scored as 999 using both human expertise and artificial intelligence assistance.

-   Text for unclear answers was revised to extract the main keywords (i.e.: most people say; I think it does not affect so much etc.), and to identify wether the answer was needed to support narrative or to provide quantitative information.

-   The keywords were pooled based on the expected type of answer (e.g.:). Three researchers independently assigned quantitative scores to textual descriptions based on predefined LIKERT scale. These expert based ratings were averaged to create a consensus dataset, which was used to establish interpretive patterns linking descriptive terms to quantitative values.

-   Answers without keywords needed for quantitative information were reviewed with Artificial Intelligence. We employed OpenAI’s GPT-5 (ChatGPT, September 2025 version) as an assistant to generalize these patterns to new responses. The model was not trained on external data but was guided by the team’s own scoring framework. For each new description, the model produced a suggested numerical score along with a written rationale. All outputs were reviewed and validated by the researchers to ensure consistency with the established coding scheme

-   Answers without keywords that were needed to support narrative (i.e.: management) were left unscored.


