---
title: "Supplementary Information for: How do extreme weather events affect fishing operations? Knowledge engineering a risk analysis with Swedish Baltic Sea fishers"

author:
  - Enrico Nicola Armelloni,:
      email: enrico.e.armelloni@gmail.com
      institute: [SLU]
      correspondence: true
  - name: Jens Olsson,
    institute: SLU
  - name: Laura Uusitalo,
    institute: LUKE
  - name: Anna Gårdmark
    institute: SLU
institute:
  - SLU: Department of Aquatic Resources, Swedish University of Agricultural Sciences, Uppsala, Sweden
  - LUKE: Fisheries and Fish Resources, Natural Resources Institute Finland (Luke), Helsinki, Finland
output: 
  pdf_document: 
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
    number_sections: false
    toc: false
header-includes:
  - \usepackage{pdfpages}
  - \usepackage[nottoc, numbib]{tocbibind}
  - \pagenumbering{gobble}
  
 
---

\vspace{12pt}

\fontsize{15}{18}\selectfont Supplementary Information A: Elicitation of parameters from fishers. Interviews plots, results and data treatment

\normalfont\normalsize

\pagenumbering{arabic}

```{=latex}
\setcounter{tocdepth}{2}
\tableofcontents
```

\setcounter{table}{0}
\renewcommand{\thetable}{A.\arabic{table}}
\renewcommand{\thefigure}{A.\arabic{figure}}

\newpage

```{r child = 'SuppInfo_A_child1_interpretation.Rmd'}
```

\newpage

```{r child = 'SuppInfo_A_child2_interviews.Rmd'}
```
